// Example hint data with solution
const hintsData = {
    1: ['Each tile will have a pair based on its border. Find the pair for each tile.', 
        'Follow the lines to find the sequence of 0s and 1s for each pair of tiles.', 
        'You will need the binary translation chart to translate the four sequences into letters.', 
        'SAVE'],
    2: ['Find a valid placement for each of the four tiles on the letter grid. Only one placement is valid for each.', 
        'Reorder the letters in order of the numbers on the tiles to form words.', 
        'Recombine the formed words on another sheet to form a final word.', 
        'NIGHTSHADE'],
    3: ['There are four pairs of drawings that are almost identical. Find the differences in each pair.', 
        'Using the grid, find which zone that each difference is found.', 
        'In the letter / number pair, the number shows the position of the letter in the word.', 
        'WORD'],
    4: ['Find the four sets of phrases that represent the four acronyms.', 
        'For each phrase, one word in the acronym does not match. Fill in the letter that doesn\'t match for each one.', 
        'The different paths show the translation between pairs of letters. Use the paths to translate the letters on the other sheet.', 
        'SECURITY'],
    5: ['Find the position for each word in the puzzle.', 
        '"C" stand for Consonant and "V" stands for Vowel.', 
        'Select only the underlined parts of each word to spell out numbers.', 
        '2579'],
    6: ['The arcs on the sheet will show you the path to take, starting at the letter "s".', 
        'Follow the exact path of each segment, jumping from letter to letter in order to spell out a word.', 
        'STEALTH'],
    7: ['There are three sets of circles that will be used together for three translations.', 
        'Once the ricles are placed in the correct positions, tranlsate the string of letters by following the path from left to right.', 
        '495'],
    8: ['There are seven fake ID cards. None of them are the real one, but they all have some pieces of information that are correct.', 
        'For each characteristic, find the data that is found most on the seven cards.', 
        'Once all information has been gathered, construct the ID number based on the template.', 
        'SBB6825'],
};

module.exports = {hintsData}