// Example hint data with solution
const hintsData = {
    1: ['Each tile will have a pair based on its border. Find the pair for each tile.', 
        'Follow the lines to find the sequence of 0s and 1s for each pair of tiles.', 
        'You will need the binary translation chart to translate the four sequences into letters.', 
        'SAVE'],
    2: ['Find a valid placement for each of the four tiles on the letter grid. Only one placement is valid for each.', 
        'Reorder the letters in order of the numbers on the tiles to form words.', 
        'Recombine the formed words on another sheet to form a final word. Some letters are given already to help find the correct position.', 
        'NIGHTSHADE'],
    3: ['Find the position for each word in the strings of Cs and Vs.', 
        '"C" stand for Consonant and "V" stands for Vowel.', 
        'Pay attention only to the underlined parts of each word.', 
        '2579'],
    4: ['There are two sets of icons that are almost identical. Find the differences in them.', 
        'Using the letter / number grid, find which zone that each difference is found.', 
        'In the letter / number pair of each difference, the number shows the position of the letter in the word.', 
        'GEAR'],
    5: ['There are seven fake ID cards. None of them are the real one, but they all have some pieces of information that are correct.', 
        'For each characteristic, find the data that is found most on the seven cards.', 
        'Once all of the highest frequency information has been gathered, construct the ID number based on the example template.', 
        'DBRBL247'],
    6: ['Find the four sets of phrases that represent the two acronyms.', 
        'For each phrase, one word in the acronym does not match. Fill in the letter that doesn\'t match for each one.', 
        'The different paths show the translation between pairs of letters. Use the paths to translate the letters "OEUI".', 
        'HACK'],
    7: ['There are three sets of circles that will be used together for three translations.', 
        'The first circle type is the pattern above the letters "NHUQ". One circle has five inputs, one has six inputs, and one has seven.',
        'Once the ricles are placed in the correct positions, tranlsate each set of four letters by following the path from left to right.', 
        '495'],
    8: ['The arcs on the sheet will show you the path to take, starting at the letter "s".', 
        'Follow the exact path of each segment, jumping from letter to letter in order to spell out a word.', 
        'STEALTH'],
};

module.exports = {hintsData}